### ISSUE TITLE
Problems piping out of a command that waits for EOF

### ISSUE THREAD

**Issue by ballesta25** [ballesta25/quash#1]
I seem to be able to chain any number of calls such as `head` that do not wait for an EOF from stdin, but calls such as `sort` are having problems (these were the same types we had problems piping into earlier) - now anything after them in the pipe chain isn't getting stdin.  For the moment, I'm assuming this still has to do with the place we close file descriptors.

**Comment by prkriley** [comment]
Did some quick searching, and it definitely looks like a close() thing.
Once ALL writers have closed the write end of a pipe (note that, when
forking after a pipe(), both parent and child must close), subsequent
read() calls will return EOF. Let's make sure everything gets closed
properly

**Comment by ballesta25** [comment]
Oops, closed wrong issue - thought this one was the `<` followed by `>` problem.

**Comment by ballesta25** [comment]
Fixed by 638e287dbc639ef07bc74fec80c73d635e18e231
